// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateBlog(ctx context.Context, descriptions sql.NullString) (Blog, error)
	DeleteBlog(ctx context.Context, id uuid.UUID) error
	GetBlog(ctx context.Context, id uuid.UUID) (Blog, error)
	ListBlog(ctx context.Context, arg ListBlogParams) ([]Blog, error)
}

var _ Querier = (*Queries)(nil)
