## For production use
app:
  name: 'GIN GONIC GOLANG CLEAN ARCHITECTURE'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'go-clean-template'

postgres:
  database_driver: "postgres"
  pool_max: 2
  pg_timezone: 'Africa/Nairobi'
  PG_URL: 'postgresql://postgres:password@localhost:5432/BLOG_DB?sslmode=disable'
